/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useAboutUsResponsiveSize from './useAboutUsResponsiveSize';

//These are the possible values for the current variant. Use this to change the currentVariant dynamically.
//Please don't modify
const variantOptions = {
  ScreenDesktop: 'ScreenDesktop',
  ScreenTablet: 'ScreenTablet',
  ScreenMobile: 'ScreenMobile',
};

const useAboutUs = () => {
  const [currentVariant, setCurrentVariant] = React.useState(
    variantOptions['ScreenDesktop']
  );

  const breakpointsVariant = useAboutUsResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  let data = { currentVariant };

  let fns = { setCurrentVariant };
  return { data, fns };
};

export default useAboutUs;
